CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source TEXT NOT NULL DEFAULT 'ring',
    device_id TEXT,
    kind TEXT NOT NULL,
    occurred_at TEXT NOT NULL,
    raw_json TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'ingested',
    triage_json TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    event_hash TEXT
);

CREATE INDEX IF NOT EXISTS idx_events_device_kind ON events(device_id, kind);
CREATE INDEX IF NOT EXISTS idx_events_occurred_at ON events(occurred_at);
CREATE UNIQUE INDEX IF NOT EXISTS idx_events_event_hash ON events(event_hash);

CREATE TABLE IF NOT EXISTS expected_context (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind TEXT NOT NULL,
    label TEXT NOT NULL,
    window_start TEXT NOT NULL,
    window_end TEXT NOT NULL,
    source TEXT NOT NULL DEFAULT 'alexa',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS labels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL REFERENCES events(id),
    pattern_key TEXT NOT NULL,
    label TEXT NOT NULL,
    confirmed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    source TEXT NOT NULL DEFAULT 'alexa'
);

CREATE INDEX IF NOT EXISTS idx_labels_pattern ON labels(pattern_key);

CREATE TABLE IF NOT EXISTS share_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brief_date TEXT NOT NULL,
    recipient TEXT NOT NULL,
    message TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS access_prefs (
    id INTEGER PRIMARY KEY,
    mode TEXT NOT NULL DEFAULT 'both',
    language TEXT NOT NULL DEFAULT 'en',
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

INSERT INTO access_prefs (id, mode, language) VALUES (1, 'both', 'en') ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS escalation_contacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label TEXT NOT NULL,
    recipient TEXT NOT NULL,
    channel TEXT NOT NULL DEFAULT 'sms',
    enabled INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    revoked_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS escalation_policy (
    id INTEGER PRIMARY KEY CHECK (id = 1),
    enabled INTEGER NOT NULL DEFAULT 0,
    timeout_seconds INTEGER NOT NULL DEFAULT 90,
    min_urgency INTEGER NOT NULL DEFAULT 7
);

INSERT INTO escalation_policy (id) VALUES (1) ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS escalation_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL,
    contact_id BIGINT,
    recipient TEXT NOT NULL,
    message TEXT NOT NULL,
    status TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS escalation_pending (
    event_id BIGINT PRIMARY KEY,
    fire_at TEXT NOT NULL,
    timeout_seconds INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);